// --------------------------------------------------------------------------------------------------------------------
// <copyright file="[SUBSYSTEM_NAME]SerializationConfigurationTypes.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package [VISUAL_STUDIO_TEMPLATE_PACKAGE_NAME] ([VISUAL_STUDIO_TEMPLATE_PACKAGE_VERSION])
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace [PROJECT_NAME]
{
    using System;

    [ExcludeFromCodeCoverage]
    [GeneratedCode("[VISUAL_STUDIO_TEMPLATE_PACKAGE_NAME]", "[VISUAL_STUDIO_TEMPLATE_PACKAGE_VERSION]")]
    public static class [SUBSYSTEM_NAME]SerializationConfigurationTypes
    {
        public static Type BsonConfigurationType => typeof([SUBSYSTEM_NAME]BsonSerializationConfiguration);

        public static Type JsonConfigurationType => typeof([SUBSYSTEM_NAME]JsonSerializationConfiguration);
    }
}