// --------------------------------------------------------------------------------------------------------------------
// <copyright file="[SUBSYSTEM_NAME]SerializationConfigurationTypes.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package [VISUAL_STUDIO_TEMPLATE_PACKAGE_ID] ([VISUAL_STUDIO_TEMPLATE_PACKAGE_VERSION])
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace [PROJECT_NAME]
{
    using System;
    using System.CodeDom.Compiler;
    using System.Diagnostics.CodeAnalysis;

    using [ORGANIZATION].[SUBSYSTEM_NAME].Serialization.Bson;
    using [ORGANIZATION].[SUBSYSTEM_NAME].Serialization.Json;

    [ExcludeFromCodeCoverage]
    [GeneratedCode("[VISUAL_STUDIO_TEMPLATE_PACKAGE_ID]", "[VISUAL_STUDIO_TEMPLATE_PACKAGE_VERSION]")]
    public static class [SUBSYSTEM_NAME]SerializationConfigurationTypes
    {
        public static Type BsonSerializationConfigurationType => typeof([SUBSYSTEM_NAME]BsonSerializationConfiguration);

        public static Type JsonSerializationConfigurationType => typeof([SUBSYSTEM_NAME]JsonSerializationConfiguration);
    }
}