// --------------------------------------------------------------------------------------------------------------------
// <copyright file="[SUBSYSTEM_NAME]DummyFactory.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in [PROJECT_NAME] source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace [PROJECT_NAME]
{
    using System;

    using FakeItEasy;

    using OBeautifulCode.AutoFakeItEasy;

    /// <summary>
    /// A Dummy Factory for types in <see cref="[PROJECT_NAME_WITHOUT_TEST_SUFFIX]"/>.
    /// </summary>
 #if ![RECIPE_CONDITIONAL_COMPILATION_SYMBOL]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("[PROJECT_NAME]", "See package version number")]
#endif
    public class [SUBSYSTEM_NAME]DummyFactory : Default[SUBSYSTEM_NAME]DummyFactory
    {
        public [SUBSYSTEM_NAME]DummyFactory()
        {
            /* Add any overriding or custom registrations here. */
        }
    }
}