// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Class1.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in $projectname$ source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace $projectname$
{
    /// <summary>
    /// bug: DOCUMENTATION HERE.
    /// </summary>
#if !$recipeconditionalcompilationsymbol$
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("$projectname$", "See package version number")]
    internal
#else
    public
#endif
    public class Class1
    {
    }
}
