// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Class1.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in [PROJECT_NAME] source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace [PROJECT_NAME]
{
    /// <summary>
    /// bug: DOCUMENTATION HERE.
    /// </summary>
#if ![RECIPE_CONDITIONAL_COMPILATION_SYMBOL]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("[PROJECT_NAME]", "See package version number")]
    internal
#else
    public
#endif
    class Class1
    {
    }
}